#!/bin/bash

love[0]=""
love[1]="https://drliveradio.akamaized.net/hls/live/2022411/p1/masterab.m3u8"
love[2]="https://drliveradio.akamaized.net/hls/live/2022411/p2/masterab.m3u8"
love[3]="https://drliveradio.akamaized.net/hls/live/2022411/p3/masterab.m3u8"
love[4]="https://drliveradio.akamaized.net/hls/live/2022411/p4bornholm/masterab.m3u8"
love[5]="http://drradio1-lh.akamaihd.net/i/p4esbjerg_9@143516/master.m3u8"
love[6]="https://drliveradio.akamaized.net/hls/live/2022411/p4fyn/masterab.m3u8"
love[7]="https://drliveradio.akamaized.net/hls/live/2022411/p4kobenhavn/masterab.m3u8"
love[8]="https://drliveradio.akamaized.net/hls/live/2022411/p4midtvest/masterab.m3u8"
love[9]="https://drliveradio.akamaized.net/hls/live/2022411/p4nordjylland/masterab.m3u8"
love[10]="https://drliveradio.akamaized.net/hls/live/2022411/p4sjaelland/masterab.m3u8"
love[11]="https://drliveradio.akamaized.net/hls/live/2022411/p4syd/masterab.m3u8"
love[12]="https://drliveradio.akamaized.net/hls/live/2022411/p4trekanten/masterab.m3u8"
love[13]="https://drliveradio.akamaized.net/hls/live/2022411/p4ostjylland/masterab.m3u8"
love[14]="https://drliveradio.akamaized.net/hls/live/2022411/p5fyn/masterab.m3u8"
love[15]="https://drliveradio.akamaized.net/hls/live/2022411/p5kobenhavn/masterab.m3u8"
love[16]="https://drliveradio.akamaized.net/hls/live/2022411/p5midtvest/masterab.m3u8"
love[17]="https://drliveradio.akamaized.net/hls/live/2022411/p5nordjylland/masterab.m3u8"
love[18]="https://drliveradio.akamaized.net/hls/live/2022411/p5sjaelland/masterab.m3u8"
love[19]="https://drliveradio.akamaized.net/hls/live/2022411/p5syd/masterab.m3u8"
love[20]="https://drliveradio.akamaized.net/hls/live/2022411/p5trekanten/masterab.m3u8"
love[21]="https://drliveradio.akamaized.net/hls/live/2022411/p5ostjylland/masterab.m3u8"
love[22]="https://drliveradio.akamaized.net/hls/live/2022411/p6beat/masterab.m3u8"
love[23]="https://drliveradio.akamaized.net/hls/live/2022411/p8jazz/masterab.m3u8"

lovel[0]=""
lovel[1]="DR P1"
lovel[2]="DR P2"
lovel[3]="DR P3"
lovel[4]="DR P4 Bornholm"
lovel[5]="DR P4 Esbjerg"
lovel[6]="DR P4 Fyn"
lovel[7]="DR P4 Kobenhavn"
lovel[8]="DR P4 Midt Vest"
lovel[9]="DR P4 Nordjylland"
lovel[10]="DR P4 Sjaelland"
lovel[11]="DR P4 Syd"
lovel[12]="DR P4 Trekanten"
lovel[13]="DR P4 Ostjlland"
lovel[14]="DR P5 Fyn"
lovel[15]="DR P5 Kobenhavn"
lovel[16]="DR P5 Midtvest"
lovel[17]="DR P5 Nordjylland"
lovel[18]="DR P5 Sjaelland"
lovel[19]="DR P5 Syd"
lovel[20]="DR P5 FTrekanten"
lovel[21]="DR P5 Ostjylland"
lovel[22]="DR P6 Beat"
lovel[23]="DR P8 Jazz"

if [ $# -eq 0 ]
then
echo "

DR Radio Denmark

usage drradio 1"
for ((i=0; i<${#love[@]}; i++))
do
echo $i . ${lovel[$i]} 
done
exit 1
fi
 mpv ${love[${1}]} | grep -E "icy-name A:|title"
